services:
  aitavalida:
    networks:
      - proxy
      - default
    labels:
      - caddy=aitavalida.azib.net
      - caddy.reverse_proxy={{upstreams 8080}}
      - caddy.reverse_proxy.lb_retries=5
      - caddy.reverse_proxy.lb_try_interval=500ms

networks:
  proxy:
    external: true
